### PR TITLE
Region.bounding_box: Remove limit of just passing two regions

### PR DESCRIPTION
**Pull request by wmanley**
`bounding_box` is associative and commutative so there's no reason
not to.

### CODE REVIEW

**Comment by drothlis** [comment]
Rebased onto master.

**Comment by drothlis** [comment]
@wmanley please review my changes to your `erode` implementation & tests (the last fixup commit).

**Comment by wmanley** [comment]
Right: so if we `dilate` with a too-large negative number we get an exception, but if we `erode` with a too-large number we get `None`.  This seems reasonable to me. +1

**Comment by drothlis** [comment]
Squashed & rebased.

**Pull request merged**
