### PR TITLE
Update core.py for #345

### PR DESCRIPTION
**Pull request by rinaldomerlo**
Proposed patch for issue:

 match_text doesn't produce debug output #345

### CODE REVIEW

**Comment by drothlis** [comment]
Hi @rinaldomerlo, thanks for the patch!

You've missed one case [here](https://github.com/stb-tester/stb-tester/pull/346/files#diff-b8db1b2ea3c8e5386ca27ac571ea7aa6L878) where there's a return earlier in the function.

Otherwise it looks good to me! The travis failure is unrelated, it's a bug in our self-tests. 

Could you also amend the commit message so that the first line has a brief summary of the change? For example: `core.py: Add debug output to match_text`

**Comment by rinaldomerlo** [comment]
Hi,

Hi @drothlis,

I didn't know what that earlier return did, so I left alone. Shall I just return a no match found for that? Or something neutral.

Rinaldo.

**Comment by drothlis** [comment]
Presumably that case is when tesseract doesn't find any text at all, so you'd want to print example the same message as you do for the "No match found" case.

**Comment by drothlis** [comment]
I just noticed that you're logging the search text instead of the complete TextMatchResult. I would prefer logging the whole TextMatchResult, in the same way that `match` logs the whole MatchResult. Something like this:

    result = TextMatchResult(ts, True, box, frame, text)
    debug("Match found: %s" % result)
    return result

and similarly for the other `return`s.

It might make sense to refactor the function so that there's a single return at the end, like [match] does.

[match]: https://github.com/stb-tester/stb-tester/blob/v24/_stbt/core.py#L630-L663

**Comment by drothlis** [comment]
Superseded by #348.

**Pull request closed without merging**
