### PR TITLE
Ubuntu 22.04 support

### PR DESCRIPTION
**Pull request by drothlis**
| Package            |  20.04 |  22.04 |
|--------------------|--------|--------|
| python3            |  3.8.2 | 3.10.4 |
| python3-opencv     |  4.2.0 |  4.5.4 |
| python3-numpy      | 1:1.17.4 | 1:1.21.5 |
| gstreamer          | 1.16.2 | 1.20.1 |
| tesseract-ocr      |  4.1.1 |  4.1.1 |
| pytest | 4.6.9 | 6.2.5 |
| pycodestyle (pep8) |  2.5.0 |  2.8.0 |
| pylint             |  2.4.4 | 2.12.2 |
| python3-astroid    |  2.3.3 |  2.9.3 |
| python3-networkx | 2.4-3ubuntu1 | 2.4-4ubuntu2 |

### CODE REVIEW

**Comment by drothlis** [comment]
The `match` failures on 22.04 are probably due to this change in OpenCV's matchTemplate:

4.2.0 (20.04) docs say:
https://docs.opencv.org/4.2.0/df/dfb/group__imgproc__object.html

> mask 	Mask of searched template. It must have the same datatype and
> size with templ. It is not set by default. Currently, only the
> TM_SQDIFF and TM_CCORR_NORMED methods are supported.

Since 4.4.0 it says:
https://docs.opencv.org/4.5.4/df/dfb/group__imgproc__object.html

> mask Optional mask. It must have the same size as templ. It must
> either have the same number of channels as template or only one
> channel, which is then used for all template and image channels. If
> the data type is CV_8U, the mask is interpreted as a binary mask,
> meaning only elements where mask is nonzero are used and are kept
> unchanged independent of the actual mask value (weight equals 1). For
> data tpye CV_32F, the mask values are used as weights. The exact
> formulas are documented in TemplateMatchModes.

**Comment by drothlis** [comment]
> If the data type is CV_8U, the mask is interpreted as a binary mask, meaning only elements where mask is nonzero are used and are kept unchanged independent of the actual mask value (weight equals 1)

This behaviour hasn't changed. As far back as 3.0.0 where support for masks was introduced, this binarisation has been done:
https://github.com/opencv/opencv/blob/3.0.0/modules/imgproc/src/templmatch.cpp#L846

And we already do the same thresholding (unnecessarily, as per the previous paragraph):
https://github.com/stb-tester/stb-tester/blob/df3f7efd8350c717f2c987fde7b3db84dab82821/_stbt/match.py#L489-L492

So that doesn't explain the failing tests.

https://github.com/opencv/opencv/pull/15214 does say that it has re-implemented `matchTemplateMask` from scratch, and there were concerns about the original implementation: https://github.com/opencv/opencv/issues/6919

**Comment by drothlis** [comment]
`test_match_all_with_transparent_reference_image` does this:

    frame = stbt.load_image("buttons-on-blue-background.png")
    matches = list(m.region for m in stbt.match_all(
        "button-transparent.png", frame=frame))

On Ubuntu 20.04 (OpenCV 4.2.0) `match_all` finds these matches:

```
Match found: MatchResult(time=None, match=True, region=Region(x=123, y=223, right=258, bottom=267), first_pass_result=0.9970706140943484, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=1, y=65, right=136, bottom=109), first_pass_result=0.996450402072181, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=177, y=119, right=312, bottom=163), first_pass_result=0.996450402072181, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=6, y=137, right=141, bottom=181), first_pass_result=0.996450402072181, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=177, y=163, right=312, bottom=207), first_pass_result=0.996450402072181, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=28, y=1, right=163, bottom=45), first_pass_result=0.9964503685616979, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=177, y=75, right=312, bottom=119), first_pass_result=0.9964503685616979, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=163, y=1, right=298, bottom=45), first_pass_result=0.9964501004778327, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
Match found: MatchResult(time=None, match=True, region=Region(x=298, y=1, right=433, bottom=45), first_pass_result=0.9964385058506623, frame=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/home/drothlis/work/stb-tester.com/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
```

On Ubuntu 22.04 (OpenCV 4.5.4) `match_all` outputs this:

```
No match found. Closest match: MatchResult(time=None, match=False, region=Region(x=298, y=0, right=433, bottom=44), first_pass_result=-216.98466257668713, frame=<Image(filename='/src/stb-tester/tests/buttons-on-blue-background.png', dimensions=434x268x3)>, image=<Image(filename='/src/stb-tester/tests/button-transparent.png', dimensions=135x44x4)>)
```

The coordinates are the same as the last match from 22.04, except y is off by 1; the big difference is **first_pass_result=-217** instead of 0.996.

**Comment by drothlis** [comment]
Note that we use match method "sqdiff", and do our own normalisation.

**Review by wmanley — APPROVED** [review]
This looked fiddly :+1:

**Pull request merged**
