### PR TITLE
STBT: control: add irtrans remote support

### PR DESCRIPTION
**Pull request by sc-stbt**
Added Irtrans support.
 - model USB V 3.8

### CODE REVIEW

**Comment by drothlis** [comment]
Hi @sc-stbt 

Thanks for the pull request!

Can you please submit the 2 changes in 2 separate pull requests? (You can remove the irtrans commit from this pull request, and make a separate branch with the irtrans commit.)

Then you'll need to make the Travis CI checks pass (click the little red "X" to see what failed). You can run these same checks on your PC by running `make check`.

Thanks!

**Comment by drothlis** [comment]
Hi @sc-stbt -- I see that you've raised #460 for the fuzzy_match functionality. If you like, I can change this pull request (#452) so that it only contains the irtrans commit. For me to change this pull request you need to enable the checkbox "[Allow edits from maintainers](https://help.github.com/assets/images/help/pull_requests/allow-maintainers-to-make-edits-sidebar-checkbox.png)".

**Comment by sc-stbt** [comment]
Good idea. I added the option

**Comment by drothlis** [comment]
I have removed the commit `STBT: core: add fuzzy_match on match_text.` because you've raised #460 for that commit. This pull request now contains the irtrans remote support.

**Comment by drothlis** [comment]
Hi @sc-stbt this pull request is failing CI too. This time it just seems to be a few style issues which you should find easy to fix.

Since I've removed a commit you'll need to re-synchronize your checkout of the branch with github first. Do something like this:

```
git checkout match_text
git fetch origin
git reset --hard origin/match_text
```

(This will lose any other work you might have on your `match_text` branch so be careful.)

Then you can fix the CI errors (see the log from travis-ci by clicking the red cross above) and `git push` to push your fixes.

**Pull request closed without merging**
