### PR TITLE
Pass regions and the inverse as mask= parameters

### PR DESCRIPTION
**Pull request by wmanley**
This enables:

```python
    SPINNER = stbt.Region(34, 433, right=44, bottom=444)
    stbt.wait_for_motion(mask=mask_out(SPINNER))
```

There is an interesting overlap here with #624.  Conceptually `mask_out(Region.ALL)` is `Region.NONE`.

**TODO:**

- [ ] Tests for `load_mask`
- [ ] Tests for `preload_mask`
- Tests for passing `region and `mask_out(Region)` to
    - [ ] `is_screen_black`
    - [ ] `wait_for_motion`
    - [ ] `press_and_wait`
- [ ] Update documentation to say that we can pass a region
- [ ] Document `mask_out`
- [ ] Change `repr(NotRegion(r))` to read `mask_out(r)`?

### CODE REVIEW

**Comment by drothlis** [comment]
Can you compose these? I've long wished for a `Mask` class, something like this:

    mask = mask_in(Region.ALL).mask_out(clock_region).mask_out(some_other_region)

Under the covers I suppose it would keep a list of Regions/NotRegions, that it can render to a numpy array. Possibly with enough smarts to calculate a bounding box that the algorithms (e.g. stbt.match) can use to limit processing to a smaller region.

**Comment by wmanley** [comment]
> Can you compose these

That would be the next step.  Once all the image processing functions convert their `mask` inputs into `ndarray`s using `load_image` we can then enhance `load_image` alone and the advantages will be felt by all the callers.

**Comment by drothlis** [comment]
Great. So I gather that `NotRegion` isn't a public API, only `mask_out` is. Maybe `load_mask` should be public API, similar to `load_image`?

**Comment by wmanley** [comment]
> Great. So I gather that `NotRegion` isn't a public API, only `mask_out` is.

Exactly

> Maybe `load_mask` should be public API, similar to `load_image`?

Maybe later. I'm anticipating a little bit of churn here.  For example we might want to return a region, ndarray tuple, or a list of regions to include for efficiency.

**Comment by drothlis** [comment]
Rebased onto main.

**Comment by drothlis** [comment]
Here's how `wait_for_motion` and `is_screen_black` behave since v28:         If you specify both `region` and `mask`, the mask must be the same size as the region (and the mask is relative to the top left corner of the region).

**Comment by drothlis** [comment]
I want to play around with the API so I don't want to go overboard on the tests just yet. I'll merge this as the existing usage is still working (at least the tests are passing) and we can add more tests and document this officially in a future pull request (which I'm working on).

**Pull request merged**
