### PR TITLE
HdmiCecControl: Raise fatal error if scan fails

### PR DESCRIPTION
**Pull request by drothlis**

### CODE REVIEW

**Comment by drothlis** [comment]
The debug logging looks like this at startup:

```
stbt_control_relay.py: libCEC version 4.0.2 loaded: compiled on Linux-4.4.0-142-generic ... , features: P8_USB, DRM, P8_detect, randr
DEBUG: libcec: Broadcast (F): osd name set to 'Broadcast'
DEBUG: libcec: connection opened, clearing any previous input and waiting for active transmissions to end before starting
DEBUG: libcec: communication thread started
DEBUG: libcec: turning controlled mode on
DEBUG: libcec: communication thread ended
INFO: libcec: connection opened
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address via ADL
DEBUG: libcec: GetPhysicalAddress - ADL returned physical address 0000
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address via nvidia driver
DEBUG: libcec: GetPhysicalAddress - nvidia driver returned physical address 0000
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address via drm files
DEBUG: libcec: GetPhysicalAddress - drm files returned physical address 0000
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address from the OS
DEBUG: libcec: GetPhysicalAddress - OS returned physical address 0000
DEBUG: libcec: unregistering all CEC clients
stbt_control_relay.py: Found a CEC adapter:"
Port:     /dev/ttyACM0
Vendor:   2548
Product:  1002
DEBUG: libcec: connection opened, clearing any previous input and waiting for active transmissions to end before starting
DEBUG: libcec: communication thread started
DEBUG: libcec: turning controlled mode on
INFO: libcec: connection opened
DEBUG: libcec: processor thread started
DEBUG: libcec: << Broadcast (F) -> TV (0): POLL
DEBUG: libcec: << f0
DEBUG: libcec: setting the line timeout to 3
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << f0
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: TV (0): device status changed into 'not present'
INFO: libcec: registering new CEC client - v4.0.2
DEBUG: libcec: detecting logical address for type 'recording device'
DEBUG: libcec: trying logical address 'Recorder 1'
DEBUG: libcec: << Recorder 1 (1) -> Recorder 1 (1): POLL
DEBUG: libcec: << 11
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 11
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: using logical address 'Recorder 1'
DEBUG: libcec: Recorder 1 (1): device status changed into 'handled by libCEC'
DEBUG: libcec: Recorder 1 (1): power status changed from 'unknown' to 'on'
DEBUG: libcec: Recorder 1 (1): vendor = Pulse Eight (001582)
DEBUG: libcec: Recorder 1 (1): CEC version 1.4
DEBUG: libcec: AllocateLogicalAddresses - device '0', type 'recording device', LA '1'
DEBUG: libcec: setting ackmask to  2
DEBUG: libcec: Recorder 1 (1): osd name set to 'stb-tester'
DEBUG: libcec: Recorder 1 (1): menu language set to 'eng�!W'
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address via ADL
DEBUG: libcec: GetPhysicalAddress - ADL returned physical address 0000
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address via nvidia driver
DEBUG: libcec: GetPhysicalAddress - nvidia driver returned physical address 0000
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address via drm files
DEBUG: libcec: GetPhysicalAddress - drm files returned physical address 0000
DEBUG: libcec: GetPhysicalAddress - trying to get the physical address from the OS
DEBUG: libcec: GetPhysicalAddress - OS returned physical address 0000
INFO: libcec: setting HDMI port to 1 on device TV (0)
DEBUG: libcec: << Recorder 1 (1) -> TV (0): POLL
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Recorder 1 (1): physical address changed from ffff to 1000
DEBUG: libcec: << Recorder 1 (1) -> broadcast (F): physical address 1000
DEBUG: libcec: << 1f:84:10:00:01
DEBUG: libcec: using persisted autonomous mode setting: 'enabled'
DEBUG: libcec: using persisted CEC version setting: '1.4'
DEBUG: libcec: using persisted logical address setting: 'Recorder 1'
DEBUG: libcec: using persisted device type setting: 'recording device'
DEBUG: libcec: using persisted logical address mask setting: '206'
DEBUG: libcec: using persisted device name setting: 'CEC Adapter'
DEBUG: libcec: using persisted physical address setting: '1000'
DEBUG: libcec: setting the OSD name to stb-tester (previous: CEC Adapter)
INFO: libcec: CEC client registered: libCEC version = 4.0.2, client version = 4.0.2, firmware version = 7, firmware build date: Wed Apr 13 10:36:11 2016 +0000, logical address(es) = Recorder 1 (1) , base device: TV (0), HDMI port number: 1, physical address: 1.0.0.0, compiled on Linux-4.4.0-142-generic ... , features: P8_USB, DRM, P8_detect, randr
DEBUG: libcec: << Recorder 1 (1) -> TV (0): OSD name 'stb-tester'
DEBUG: libcec: << Recorder 1 (1) -> TV (0): POLL
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: not sending command 'set osd name': destination device 'TV' marked as not present
DEBUG: libcec: << requesting power status of 'TV' (0)
DEBUG: libcec: << Recorder 1 (1) -> TV (0): POLL
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
stbt_control_relay.py: Connection to CEC adapter opened
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: not sending command 'give device power status': destination device 'TV' marked as not present
DEBUG: libcec: << Recorder 1 (1) -> TV (0): POLL
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: << Recorder 1 (1) -> Recorder 2 (2): POLL
DEBUG: libcec: << 12
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 12
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Recorder 2 (2): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Tuner 1 (3): POLL
DEBUG: libcec: << 13
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 13
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Tuner 1 (3): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Playback 1 (4): POLL
DEBUG: libcec: << 14
DEBUG: libcec: >> POLL sent
DEBUG: libcec: Playback 1 (4): device status changed into 'present'
DEBUG: libcec: << Recorder 1 (1) -> Audio (5): POLL
DEBUG: libcec: << 15
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 15
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Audio (5): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Tuner 2 (6): POLL
DEBUG: libcec: << 16
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 16
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Tuner 2 (6): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Tuner 3 (7): POLL
DEBUG: libcec: << 17
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 17
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Tuner 3 (7): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Playback 2 (8): POLL
DEBUG: libcec: << 18
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 18
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Playback 2 (8): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Recorder 3 (9): POLL
DEBUG: libcec: << 19
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 19
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Recorder 3 (9): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Tuner 4 (A): POLL
DEBUG: libcec: << 1a
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 1a
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Tuner 4 (A): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Playback 3 (B): POLL
DEBUG: libcec: << 1b
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 1b
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Playback 3 (B): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Reserved 1 (C): POLL
DEBUG: libcec: << 1c
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 1c
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Reserved 1 (C): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Reserved 2 (D): POLL
DEBUG: libcec: << 1d
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 1d
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Reserved 2 (D): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> Free use (E): POLL
DEBUG: libcec: << 1e
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 1e
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
DEBUG: libcec: Free use (E): device status changed into 'not present'
DEBUG: libcec: << Recorder 1 (1) -> TV (0): POLL
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: << 10
DEBUG: libcec: CEC transmission - received response - TRANSMIT_FAILED_ACK
DEBUG: libcec: >> POLL not sent
stbt_control_relay.py: HDMI-CEC scan complete.  Found [4]
DEBUG: libcec: << requesting vendor ID of 'Playback 1' (4)
DEBUG: libcec: << 14:8c
DEBUG: libcec: >> 4f:87:00:10:fa
DEBUG: libcec: Playback 1 (4): vendor = Unknown (0010fa)
DEBUG: libcec: expected response received (87: device vendor id)
DEBUG: libcec: << requesting OSD name of 'Playback 1' (4)
DEBUG: libcec: << 14:46
DEBUG: libcec: >> Playback 1 (4) -> Broadcast (F): device vendor id (87)
DEBUG: libcec: >> 41:47:47:61:6d:65:73:20:52:6f:6f:6d
stbt_control_relay.py: HDMI-CEC: Chose to talk to device 4 'Games Room'
INFO: stbt-control-relay started up with output 'hdmi-cec'
DEBUG: libcec: Playback 1 (4): osd name set to 'Games Room'
DEBUG: libcec: expected response received (47: set osd name)
DEBUG: libcec: >> Playback 1 (4) -> Recorder 1 (1): set osd name (47)
```

And like this for a keypress:

```
DEBUG: Received SEND_ONCE KEY_HOME
DEBUG: libcec: << 14:44:09
DEBUG: libcec: << 14:45
stbt_control_relay.py: Pressed KEY_HOME
```

**Comment by drothlis** [comment]
I wondered if calling `RescanActiveDevices()` was necessary when we call `rescan()` from the constructor, as we have just initialised libcec:

https://github.com/stb-tester/stb-tester/blob/35590836ed4938809c72a7c37f606d8b65924be0/_stbt/control_gpl.py#L334-L336

I removed `RescanActiveDevices()` and checked the diff in the debug output from libcec -- no change in the debug output. It still found the CEC device. I didn't notice any difference in startup time, though, so I've left it in. Presumably it *is* necessary for subsequent calls to `rescan()`.

**Comment by drothlis** [comment]
The example in https://github.com/Pulse-Eight/libcec/blob/libcec-3.0.1/src/pyCecClient/pyCecClient.py calls `GetActiveDevices` (from its `scan` function) but never calls `RescanActiveDevices`.

Both `RescanActiveDevices` and `GetActiveDevices` end up calling `CCECBusDevice::GetStatus` but the former sets `bForcePoll=true`.

Anyway, this was just an idle investigation not related to this pull request. I'll stop now, I don't want to risk unnecessary changes.

**Review by wmanley — APPROVED** [review]
Yeah, this looks really good. As you say, the logging will be really useful, particularly the bits about enumerating the CEC bus.

Merging.

**Pull request merged**
