### PR TITLE
.travis.yml: Use Travis CI's new docker infrastructure

### PR DESCRIPTION
**Pull request by drothlis**
See http://blog.travis-ci.com/2015-08-19-using-docker-on-travis-ci/

This commit is to test whether we get Ubuntu 14.04 even though we don't actually use docker.

TODO:

- [x] Make CI pass

### CODE REVIEW

**Comment by drothlis** [comment]
The Travis [results](https://travis-ci.org/stb-tester/stb-tester/builds/79128586) look mostly OK! Just a few terminal-related issues to resolve: Printing unicode characters, and running the interactive `stbt control` in a terminal window that's wide enough.

**Comment by wmanley** [comment]
This will be really useful for running test-stbt-docker.sh from #304.

**Comment by wmanley** [comment]
The last? problem seems to be that `test_clock_visualisation` fails intermittently with:

    test_clock_visualisation... FAIL
    ...
    stbt-run: OCR in region Region(x=5, y=5, width=195, height=30) read '08:35:21.17'.
    stbt-run: OCR in region Region(x=5, y=5, width=195, height=30) read '08:35:23.25'.
    FAIL: verify.py: AssertionError: Unexpected time diff 0:00:02.100000 between 2015-09-18 08:35:23.200000 and 2015-09-18 08:35:21.100000
    Traceback (most recent call last):
      File "/home/travis/build/stb-tester/stb-tester/tests/test-install/libexec/stbt/stbt-run", line 107, in <module>
        execfile(_filename)
      File "/tmp/stb-tester.pNi/verify.py", line 16, in <module>
        assert seconds(0.9) < diff < seconds(2), 	    "Unexpected time diff %s between %s and %s" % (diff, end, start)
    AssertionError: Unexpected time diff 0:00:02.100000 between 2015-09-18 08:35:23.200000 and 2015-09-18 08:35:21.100000
    ...

**Comment by wmanley** [comment]
From the previous failures I've seen the time diff seems to be fairly consistently just slightly over 2s.  It suggests a change in behaviour has added 1s of latency to our pipeline here.

**Comment by drothlis** [comment]
The hope that moving to Ubuntu 14.04 would avoid the intermittent python-gi
errors like "was expecting Gst.Structure but got Structure" isn't entirely
true: [This build](https://travis-ci.org/stb-tester/stb-tester/builds/83691831) said:

```
Traceback (most recent call last):
  File "/home/travis/build/stb-tester/stb-tester/tests/test-install/libexec/stbt/stbt-run", line 107, in <module>
    execfile(_filename)
  File "/tmp/stb-tester.5mz/test.py", line 3, in <module>
    match_result = stbt.match("/home/travis/build/stb-tester/stb-tester/tests/videotestsrc-redblue.png")
  File "/home/travis/build/stb-tester/stb-tester/tests/test-install/libexec/stbt/stbt/__init__.py", line 139, in match
    return _dut.match(image, frame, match_parameters, region)
  File "/home/travis/build/stb-tester/stb-tester/tests/test-install/libexec/stbt/_stbt/core.py", line 639, in match
    with _numpy_from_sample(frame, readonly=True) as npframe:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/travis/build/stb-tester/stb-tester/tests/test-install/libexec/stbt/_stbt/core.py", line 1235, in _numpy_from_sample
    flags = Gst.MapFlags.READ
AttributeError: type object 'GstMapFlags' has no attribute 'READ' 
```

Merging this will still be worth it of course -- to be testing on Ubuntu 14.04
which is the distro we actually support.

**Comment by drothlis** [comment]
I added some logging, and it seems that the change in `test_clock_visualisation`'s timings is because tesseract takes longer to run (just over 1s):

    **** time.time(): 1444052174.11
    stbt-run: OCR in region Region(x=5, y=5, width=195, height=30) read '13:36:14.09'.
    **** time.time(): 1444052175.18
    **** time.time(): 1444052176.18
    stbt-run: OCR in region Region(x=5, y=5, width=195, height=30) read '13:36:16.12'.
    **** time.time(): 1444052177.38

I've pushed a fix to the test (3004877).

**Comment by drothlis** [comment]
Now the failures are in `test_that_stbt_camera_calibrate_corrects_for_geometric_distortion` and `test_illumination_compensation`. I think they're intermittent. These tests aren't run in CI currently so it isn't surprising.

**Comment by drothlis** [comment]
I suppose we could merge this and fix the failures as part of your [camera-opengl](https://github.com/wmanley/stb-tester/commits/camera-opengl) branch.

**Comment by drothlis** [comment]
...or we could disable the `stbt camera` tests and merge.

**Comment by wmanley** [comment]
> tesseract takes longer to run

What a shame.  I guess it's because its running on a more contended machine.

**Comment by wmanley** [comment]
> ...or we could disable the stbt camera tests and merge.

Agreed.  This is good because it decouples this work from my branch.

**Pull request merged**
