### PR TITLE
[WIP]Test on UI elements by color range

### PR DESCRIPTION
**Pull request by JNan86**
### Challenges
I would like to share some functions to test on UI elements by color range which I've been using for a long time in our test pack. I implemented the functions due to the following challenges:

I wanted to match a red icon which appears when recording is enabled on a channel from planner. We needed to test the same software on two different STBs, the UI layout were exactly the same but there is slight color difference which is enough to cause the image matching to fail. As I only wanted to quickly check whether the icon pops up when the recording is started, so I wrote the method `get_mask_by_color_range` to filter the frame to get a mask, then wrote another method `get_color_existence` to check whether the color is existed. In this way, I could make my test code generic for both STBs.

Later on in another project, we needed to determine the selected tab on a top level menu. The tabs do not have the same size and the size depends on how long the text is. The color of a tab will change when the cursor is on it. In this case, it was too verbose to match by the tab images, so again I used the method `get_mask_by_color_range` to get a mask highlighting the tab selected, and based on that, I wrote the method `get_colored_box_region` to find the bounding region of the selected tab then use OCR to read the content of the tab.

### List of class and functions implemented
+ `stbt.Color` the class to represent a specific color, defaults to be instantiated by HSV but can be parsed from BGR
+ `stbt.get_mask_by_color_range` the method to get a mask highlighting the area where the range of color exists
+ `stbt.get_color_existence` (I have not yet migrated this function) the method to determine whether the specified color
is existed in a given `stbt.Region`
+ `stbt.get_colored_box_region` the method to find the bounding `stbt.Region` of the colored area

Please check the docstrings for more details.

### Todo
- [ ] To migrate `get_color_existence`
- [ ] To implement self-test
- [ ] To discuss whether there is a need to wrap the matching results into something like `stbt.MatchResult`
- [ ] To pass `make check`

### Things to note
+ HSV was used to easier define a range of color.
+ In terms of performance, I'm not sure whether all methods can finish processing within 1/25 second on all platforms but for functional test requirements, this is not a big deal. Matching by color is generally faster and more reliable.

It seems like color matching/recognition is a common requirement for test development. I'm not too sure whether we are trying to solve the same problem? #592

### CODE REVIEW

**Comment by msiden** [comment]
This does indeed sound quite similar to what I proposed in #592. I think my proposal may be more basic. As for the get_colored_box_region method I am doing similar things in my test pack and can confirm that it is a very elegant and powerful feature.

**Comment by drothlis** [comment]
Hi @JNan86! Thanks for your contribution, it looks like useful stuff.

I haven't reviewed the code or the API yet, but could you please attach some screenshots to issue #590, of the kind of things that you need to detect? You can crop them to remove sensitive information. I've already attached one example. We will need these to (1) design an API that meets all (most) colour-related needs, and (2) for unit tests.

@msiden you too if you can.

**Comment by drothlis** [comment]
> The color of a tab will change when the cursor is on it. [...] `get_colored_box_region` to find the bounding region of the selected tab then use OCR to read the content of the tab.

See also `find_boxes` and `find_solid_coloured_boxes` from pull request #519 for a different approach (using edge detection) for finding a box (rectangle) by colour.

**Comment by wmanley** [comment]
Closing, we have this now: https://stb-tester.com/manual/python-api#stbt.find_regions_by_color

**Pull request closed without merging**
