### PR TITLE
ocr_eq docstring: Document ocr_eq.replacements and ocr_eq.normalize

### PR DESCRIPTION
**Pull request by drothlis**

### CODE REVIEW

**Comment by drothlis** [comment]
The generated sphinx documentation looks like this:

image

**Comment by drothlis** [comment]
@wmanley what do you think about documenting these?

**Review by wmanley — COMMENTED** [review]
I'm happy for this to be public as long as VSCode understands it.  If not then it would be better as `ocr_eq_replacements`.

**Comment by drothlis** [comment]
> I'm happy for this to be public as long as VSCode understands it. If not then it would be better as `ocr_eq_replacements`.

VSCode doesn't understand it — doesn't autocomplete, doesn't catch typos — but at least it doesn't mark code like this as an error:

    stbt.ocr_eq.replacements["x"] = "X"

It thinks it's a function of type `Any`:

image

**Comment by wmanley** [comment]
https://github.com/python/mypy/issues/2087

**Comment by wmanley** [comment]
I've just realised that there's a subtlety here when adding additional replacements.  You could do:

```py
ocr_eq.replacements["İ"] = "I"
```

But then this would fail:

```py
ocr_eq("İ", "I")
```

Because that would now be equivalent to `"I" == "l"`

**Comment by drothlis** [comment]
Or we could run through the replacements twice?

**Comment by drothlis** [comment]
> I've just realised that there's a subtlety here when adding additional replacements.

Fixed in #823.

**Pull request merged**
